version: "3"
services:
  trade_bot:
    build: .
    volumes:
      - ./.git:/app/.git:ro
      - ./scripts:/app/scripts:ro
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./tmp:/tmp/alphapool-trader
    working_dir: /app
    environment:
      CCXT_EXCHANGE: ${CCXT_EXCHANGE:-ftx}
      CCXT_API_KEY: ${CCXT_API_KEY}
      CCXT_API_SECRET: ${CCXT_API_SECRET}
      CCXT_SUBACCOUNT: ${CCXT_SUBACCOUNT}
      ALPHAPOOL_LEVERAGE: ${ALPHAPOOL_LEVERAGE:-1.0}
      ALPHAPOOL_LOG_LEVEL: debug
      ALPHAPOOL_MODEL_ID: ${ALPHAPOOL_MODEL_ID}
    command: python -m src.main
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    extra_hosts:
      - "host.docker.internal:host-gateway"
