name: Publish Docker image

on:
  push:
    branches:
      - 'feature/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >>$GITHUB_ENV
      - run: echo "DOCKER_TAG=${BRANCH////_}" >> $GITHUB_ENV

      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.DOCKER_TAG }}
